"""empty message

Revision ID: 93f39f92ac87
Revises: 
Create Date: 2021-10-28 00:02:01.256167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f39f92ac87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrower',
    sa.Column('idBorrower', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=45), nullable=True),
    sa.Column('tel_num', sa.String(length=45), nullable=True),
    sa.Column('property', sa.String(length=45), nullable=True),
    sa.Column('confidant', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idBorrower')
    )
    op.create_table('types_credit',
    sa.Column('idType', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('condition', sa.String(length=45), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('term', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('idType')
    )
    op.create_table('credit',
    sa.Column('idCredit', sa.Integer(), nullable=False),
    sa.Column('idType', sa.Integer(), nullable=True),
    sa.Column('idBorrower', sa.Integer(), nullable=True),
    sa.Column('soum', sa.Integer(), nullable=True),
    sa.Column('date_of_issue', sa.Date(), nullable=True),
    sa.Column('canceled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['idBorrower'], ['borrower.idBorrower'], ),
    sa.ForeignKeyConstraint(['idType'], ['types_credit.idType'], ),
    sa.PrimaryKeyConstraint('idCredit')
    )
    op.create_table('repayment',
    sa.Column('idRepayment', sa.Integer(), nullable=False),
    sa.Column('idCredit', sa.Integer(), nullable=True),
    sa.Column('soum', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['idCredit'], ['credit.idCredit'], ),
    sa.PrimaryKeyConstraint('idRepayment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment')
    op.drop_table('credit')
    op.drop_table('types_credit')
    op.drop_table('borrower')
    # ### end Alembic commands ###
