"""empty message

Revision ID: be8e21e91c6a
Revises: 
Create Date: 2021-12-09 15:17:45.086845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be8e21e91c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bank',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('ClientName', sa.String(length=45), nullable=True),
    sa.Column('firstName', sa.String(length=45), nullable=True),
    sa.Column('lastName', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_borrower', sa.Integer(), nullable=True),
    sa.Column('id_bank', sa.Integer(), nullable=True),
    sa.Column('loan_status', sa.Boolean(), nullable=True),
    sa.Column('loan_date', sa.String(length=45), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bank'], ['Bank.bank_id'], ),
    sa.ForeignKeyConstraint(['id_borrower'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('bank')
    op.drop_table('credit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_borrower', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_bank', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('loan_date', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('loan_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_rate', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_bank'], ['bank.bank_id'], name='credit_ibfk_2'),
    sa.ForeignKeyConstraint(['id_borrower'], ['user.id'], name='credit_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('bank',
    sa.Column('bank_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bank_id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ClientName', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.drop_table('Credit')
    op.drop_table('User')
    op.drop_table('Bank')
    # ### end Alembic commands ###
