"""empty message

Revision ID: c20d99aca24f
Revises: 
Create Date: 2021-11-18 16:01:26.698239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20d99aca24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bank',
    sa.Column('bank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bank_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('ClientName', sa.String(length=45), nullable=True),
    sa.Column('firstName', sa.String(length=45), nullable=True),
    sa.Column('lastName', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_borrower', sa.Integer(), nullable=True),
    sa.Column('id_bank', sa.Integer(), nullable=True),
    sa.Column('loan_status', sa.Boolean(), nullable=True),
    sa.Column('loan_date', sa.String(length=45), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_bank'], ['Bank.bank_id'], ),
    sa.ForeignKeyConstraint(['id_borrower'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Credit')
    op.drop_table('User')
    op.drop_table('Bank')
    # ### end Alembic commands ###
